# configs/models/anthropic.yaml - FIXED STRUCTURE
models:
  claude_3_opus:
    display_name: "Claude 3 Opus"
    version: "claude-3-opus-20240229"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 200000
    context_window: 200000
    strengths: 
      - "Long context handling"
      - "Advanced reasoning"
      - "Instruction following"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_output_tokens: 4096
    cost:
      input_per_1k: 15.0
      output_per_1k: 75.0
    provider: "anthropic"

  claude_3_5_sonnet:
    display_name: "Claude 3.5 Sonnet"
    version: "claude-3-5-sonnet-20240620"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 200000
    context_window: 200000
    strengths:
      - "Balance of speed and quality"
      - "Task planning"
      - "Few-shot learning"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_output_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "anthropic"

  claude_3_5_haiku:
    display_name: "Claude 3.5 Haiku"
    version: "claude-3-5-haiku-20240307"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 200000
    context_window: 200000
    strengths:
      - "Speed"
      - "Cost efficiency"
      - "Short-form responses"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_output_tokens: 4096
    cost:
      input_per_1k: 0.25
      output_per_1k: 1.25
    provider: "anthropic"

  claude_3_7_sonnet:
    display_name: "Claude 3.7 Sonnet"
    version: "claude-3-7-sonnet-20240620"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 200000
    context_window: 200000
    strengths:
      - "Latest capabilities"
      - "Enhanced reasoning"
      - "Improved factual knowledge"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_output_tokens: 4096
    cost:
      input_per_1k: 5.0
      output_per_1k: 25.0
    provider: "anthropic"