# configs/models/cohere.yaml - CORRECTED MODEL NAMES AND v2 ENDPOINTS
models:
  command-a-03-2025:
    display_name: "Cohere Command A"
    version: "command-a-03-2025"  # This is the actual model ID for API calls
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Agent-oriented capabilities"
      - "Tool use and function calling"
      - "Task automation"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command-r-plus-08-2024:
    display_name: "Cohere Command R+ 08-2024"
    version: "command-r-plus-08-2024"  # This is the actual model ID for API calls
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Citation capabilities"
      - "Hallucination reduction"
      - "Advanced reasoning"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command-r-plus-04-2024:
    display_name: "Cohere Command R+ 04-2024"
    version: "command-r-plus-04-2024"  # This is the actual model ID for API calls
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Citation capabilities"
      - "Hallucination reduction"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command-r-plus:
    display_name: "Cohere Command R+"
    version: "command-r-plus"  # This is the actual model ID for API calls
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Citation capabilities"
      - "Hallucination reduction"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command-r-08-2024-v004:
    display_name: "Cohere Command R 08-2024"
    version: "command-r-08-2024"  # This is the actual model ID for API calls
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
      - "Factual accuracy"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"

  command-r-08-2024-v003:
    display_name: "Cohere Command R 08-2024 v003"
    version: "command-r-08-2024"  # Same model ID as v004, just different config name
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
      - "Factual accuracy"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"

  command-r-03-2024:
    display_name: "Cohere Command R 03-2024"
    version: "command-r-03-2024"  # This is the actual model ID for API calls
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"

  command-r:
    display_name: "Cohere Command R"
    version: "command-r"  # This is the actual model ID for API calls
    api_key_env: "COHERE_API_KEY"
    api_url: "https://api.cohere.com/v2/chat"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"