# configs/models/openai.yaml - CORRECTED WITH REAL MODEL NAMES
models:
  gpt-4o:
    display_name: "GPT-4o"
    version: "gpt-4o"  # This is the correct name
    api_key_env: "OPENAI_API_KEY"
    org_id_env: "OPENAI_ORG_ID"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Multimodal capabilities"
      - "Fast inference"
      - "Balanced performance"
      - "Vision processing"
    defaults:
      temperature: 0.7
      top_p: 1.0
      max_tokens: 4096
    cost:
      input_per_1k: 5.0
      output_per_1k: 15.0
    provider: "openai"

  gpt-4-turbo:
    display_name: "GPT-4 Turbo"
    version: "gpt-4-turbo"  # This is the correct name
    api_key_env: "OPENAI_API_KEY"
    org_id_env: "OPENAI_ORG_ID"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Speed optimization"
      - "Cost efficiency"
      - "General purpose reasoning"
      - "Knowledge cutoff improvements"
    defaults:
      temperature: 0.7
      top_p: 1.0
      max_tokens: 4096
    cost:
      input_per_1k: 10.0
      output_per_1k: 30.0
    provider: "openai"

  gpt-4:
    display_name: "GPT-4"
    version: "gpt-4"  # This is the correct name
    api_key_env: "OPENAI_API_KEY"
    org_id_env: "OPENAI_ORG_ID"
    max_tokens: 8192
    context_window: 8192
    strengths:
      - "Latest reasoning abilities"
      - "Enhanced creative generation"
      - "Improved instruction following"
      - "Code generation"
    defaults:
      temperature: 0.7
      top_p: 1.0
      max_tokens: 4096
    cost:
      input_per_1k: 30.0
      output_per_1k: 60.0
    provider: "openai"

  gpt-4.1:
    display_name: "GPT-4.1"
    version: "gpt-4.1"  # This is the correct name
    api_key_env: "OPENAI_API_KEY"
    org_id_env: "OPENAI_ORG_ID"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Advanced reasoning"
      - "Mathematical problem solving"
      - "Coding capabilities"
      - "Scientific reasoning"
      - "Logical deduction"
    defaults:
      temperature: 1.0  # O1 models have fixed temperature
      top_p: 1.0
      max_tokens: 4096
    cost:
      input_per_1k: 15.0
      output_per_1k: 60.0
    provider: "openai"

  gpt-4.5-preview:
    display_name: "gpt-4.5-preview"
    version: "gpt-4.5-preview"  # This is the correct name (not o1-pro)
    api_key_env: "OPENAI_API_KEY"
    org_id_env: "OPENAI_ORG_ID"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Advanced reasoning (smaller)"
      - "Faster than O1-preview"
      - "Cost efficient reasoning"
      - "Mathematical problem solving"
    defaults:
      temperature: 1.0  # O1 models have fixed temperature
      top_p: 1.0
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 12.0
    provider: "openai"

  gpt-3.5-turbo:
    display_name: "GPT-3.5 Turbo"
    version: "gpt-3.5-turbo"
    api_key_env: "OPENAI_API_KEY"
    org_id_env: "OPENAI_ORG_ID"
    max_tokens: 4096
    context_window: 16385
    strengths:
      - "Cost efficient"
      - "Fast response times"
      - "Good for simple tasks"
    defaults:
      temperature: 0.7
      top_p: 1.0
      max_tokens: 4096
    cost:
      input_per_1k: 0.5
      output_per_1k: 1.5
    provider: "openai"