# configs/models/cohere.yaml - FIXED STRUCTURE (rename from others.yaml)
models:
  command_a_03_2025:
    display_name: "Cohere Command A"
    version: "command-a-03-2025"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Agent-oriented capabilities"
      - "Tool use and function calling"
      - "Task automation"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command_r_plus_08_2024:
    display_name: "Cohere Command R+ 003"
    version: "command-r-plus-08-2024"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Citation capabilities"
      - "Hallucination reduction"
      - "Advanced reasoning"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command_r_plus_04_2024:
    display_name: "Cohere Command R+ 002"
    version: "command-r-plus-04-2024"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Citation capabilities"
      - "Hallucination reduction"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command_r_plus:
    display_name: "Cohere Command R+ 001"
    version: "command-r-plus"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Citation capabilities"
      - "Hallucination reduction"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 3.0
      output_per_1k: 15.0
    provider: "cohere"

  command_r_08_2024_v004:
    display_name: "Cohere Command R 004"
    version: "command-r-08-2024"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
      - "Factual accuracy"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"

  command_r_08_2024_v003:
    display_name: "Cohere Command R 003"
    version: "command-r-08-2024"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
      - "Factual accuracy"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"

  command_r_03_2024:
    display_name: "Cohere Command R 002"
    version: "command-r-03-2024"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"

  command_r:
    display_name: "Cohere Command R 001"
    version: "command-r"
    api_key_env: "COHERE_API_KEY"
    max_tokens: 128000
    context_window: 128000
    strengths:
      - "Enterprise focus"
      - "Research capabilities"
      - "Knowledge retrieval"
    defaults:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 4096
    cost:
      input_per_1k: 1.0
      output_per_1k: 5.0
    provider: "cohere"