# configs/test_config.yaml - Updated with all models
version: 1.0

# Model configuration directory
model_config_dir: "configs/models"
test_cases_dir: "test_cases"

# All models from your configuration files - CORRECTED NAMES
selected_models:
  # OpenAI models - CORRECTED
    - gpt-4o
    - gpt-4-turbo
    - gpt-4
    - gpt-4.1
    - gpt-4.5-preview  # Changed from o1_pro
    - gpt-3.5-turbo  # Added working model
  
  # Anthropic models
    - claude-opus-4-20250514
    - claude-sonnet-4-20250514
    - claude-3-7-sonnet-20250219
    - claude-3-5-sonnet-20241022
    - claude-3-5-sonnet-20240620
    - claude-3-5-haiku-20241022
    - claude-3-haiku-20240307
    - claude-3-opus-20240229
  
  # Google models
  # - gemini-2.5-pro-preview-03-25
  # - gemini-2.5-pro-exp-03-25
  # - gemini-2.5-pro-preview-05-06
  # - gemini-2.5-flash-preview-04-17
  # - gemini-2.5-flash-preview-04-17-thinking
  # - gemini-2.0-pro-exp
  # - gemini-2.0-flash
  # - gemini-2.0-flash-thinking-exp
  # - gemini-1.5-pro
  # - gemini-1.5-flash
  
  # Mistral models
    - mistral-small-latest
    - mistral-medium-latest
    - mistral-large-latest
  
  # Cohere models
    - command-a-03-2025
    - command-r-plus-08-2024
    - command-r-plus-04-2024
    - command-r-plus
    - command-r-08-2024-v004
    - command-r-08-2024-v003
    - command-r-03-2024
    - command-r

# Test categories
categories:
  - ppt
  - content
  - creativity
  - efficiency
  - formatting
  - consistency
  - personalization

# Test execution settings
parallel_execution: false
retry_count: 2  # Reduced for faster testing
timeout: 200  # Reduced timeout

# Evaluation metrics
evaluation:
  score_weights:
    ppt:
      relevance: 0.2
      slide_structure: 0.2
      visual_elements: 0.15
      slide_transitions: 0.1
      formatting_consistency: 0.15
      content_organization: 0.2
    content:
      accuracy: 0.25
      comprehensiveness: 0.2
      relevance: 0.2
      depth: 0.15
      clarity: 0.2
    creativity:
      novelty: 0.3
      uniqueness: 0.3
      adaptability: 0.2
      innovation: 0.2
    efficiency:
      token_usage: 0.4
      instruction_following: 0.3
      completeness: 0.3
    formatting:
      markdown_correctness: 0.4
      table_formatting: 0.3
      list_formatting: 0.3
    consistency:
      style_consistency: 0.4
      tone_consistency: 0.3
      branding_consistency: 0.3
    personalization:
      audience_targeting: 0.4
      industry_adaptation: 0.3
      customization: 0.3

# Reporting configuration
reporting:
  generate_charts: true
  include_detailed_metrics: true
  highlight_top_performers: true